language: go
go:
- '1.0'
- '1.3'
deploy:
  provider: releases
  api_key:
    secure: Zvn4olNj67sPj0+Ys/9O/ttfhYFXA2TDQ2g1Xbwxq/7AViIxVbizLM/5MHfFLYhEC5h/CqXNAUWUCQ5igRqqEaMfQFGGG+gZh/V/h4fJbmQVSH06Kobd3H8f5cMSyEfna/Vl2cBokwPrU+XZ/UM3Uw1XddMvFw3hLLPCE711b3X41WD5vlr5dPVsKv1Guk84K4o5FoWxPrvcP7MJoCLjtrXlb7+R51ceK+d2QKlxDBPtR+9y8flayn8tNVYsd9qCdmcwoCv2LU32t/dC1SI3Fl0lPnIkrvZqdZTXJjZTYGlcwD9DkNrj0eLjYXeLuwUKaaHLmPpRPjOTjq3JTgkkFk2EeHi3b23Ikyl98iWZgFG6qfxoq1RzNtbPdeV/1SiDq2EFeqzIE374yDCqZ4mytIhoUwFPGX77YXMOjFxgImZ/8ucfKOw+B7bNp/evviSrnt9LbDW0emv0IEKQdDcZSPi4tPhzq31QScVDsdeZKRqeM9+U/yPA390DWsnRPnfE67ubfbVcwcGxODRwtatQrwIgTAhHTMZcXapV4mYiIb3CAfjB8Wn4xMkGaI4drIYwJChU5fTmy3BFl5F9PVW53g/xVL1g3cMOw/FiAyO+jh+16jJVHrazRNXEu2Cb2gs62GhhMb7S8NSTEF2KavcnOorDhy2t+PX+ztm8w+U+RWo=
  file: dipperin
  on:
    repo: yangchuang123456/dipperin-core
