language: go
go:
  - 1.x
cache: false #不使用cache
#cache: ccache

sudo: required # 使用容器进行编译，速度更快
services:
  - docker
git:
  submodules: false # 不运行 git submodules 命令

before_install:
  - docker pull karalabe/xgo-latest
  - docker ps -a
  - go get github.com/karalabe/xgo

install: true # 跳过 install 阶段，因为我已经定义了 before_install。其实 go 项目是需要安装依赖的，只是我放到了下面的 make mycli 命令中做

#script: make travis-test && make compile # 先运行测试，然后交叉编译
script: make compile

deploy:
  provider: releases
  api_key:
    secure: etgmmEzi1ftIKP0UPMzJLNpbhZyGvgAwkGI3SvaQhofmynzD97lHgJDGOfSxi9cRuUcC1QLjnUQLRdpgdLR0V1DD6y57FYvoJLn2j3fhY7PJNy3F/YbwkEnYW+70SmEvvpOlk3AD7hx6EF8DLazdhSVwQfHcJuUMAcAyx20wDBBXqmweZo4kCM/SDxGkShvDsB4GK8gwAlD+zK8dL4uXEGojQTN9SgSoPVILlpHctlEfUNkWpAse50zpwfH0VwOCx4N7rVS1a52j2yZe9kT67WbOo/okq9/Kz7OUnaIZLdZnovYrtX4T0tW2peNXo3QROdsnCMrs3rzFHQS1G3VpBJr9BfXy3ZxiyiXOMQMZGNuA/CGFvbjo/4lvnx3KtvJMP0xN92hzBNJo1mITsAbqamMRPR0/SYm60hcFWMpG+p7FLa3ZqhaERR48nF9okYLL6MtT5L6cX2VlPE7Qi192cY02FLqhovL/9UrZLE96AM+vX4PgyseJM6nCH8sVi3ymKMVloPAwEzbqz+Abr4VOroMVb2KzKFL+GliqfSsqMa57xx7ZTxzcrQl/GeH1vMpjX9s8nBSVVhaYxtCxiRPgiEpHd2YLWGWxyQQP5fF99C8w8CEd82a+vODrHP8vfg5n3ZF5V6mHlA9nypG4iIHjnw4iTKmm42uzAsmvdVECMNc=

  file:
    - "dipperin-core-darwin-10.6-amd64"
    - "dipperin-core-linux-amd64"
    - "dipperin-core-windows-4.0-amd64.exe"
  skip_cleanup: true # 因为要上传可执行文件到 release，所以不能自动把这个文件清除
  on:
    repo: yangchuang123456/dipperin-core
    branch: master
    tags: true   #git tag 时发布
